export const ROUTES = {
  LANDING: '/',
  DRAW: '/sortear',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_CHANGE: '/verify-email-change',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  HOME: '/app',
  SEARCH: '/app/search',
  LIST: '/app/list',
  PROFILES: '/app/profiles',
  ONBOARDING: '/app/onboarding',
}
